name: pipeline

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Package
      run: mvn package  
